[build]
default-target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
dockerfile = "cross/aarch64-unknown-linux-gnu.Dockerfile"


[build.env]
passthrough = [
    "RUSTFLAGS",
#    "RUSTFLAGS=-C target-feature=+crt-static"
]