[build]
default-target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
dockerfile = "cross/aarch64.Dockerfile"

[target.armv7-unknown-linux-gnueabihf]
dockerfile = "cross/armv7.Dockerfile"


[build.env]
passthrough = [
    "RUSTFLAGS",
#    "RUSTFLAGS=-C target-feature=+crt-static"
]